// Copies Loadout's third-party browser files out of node_modules and builds
// its icon sprite. Run `npm install && npm run vendor` after bumping a version
// in package.json, then commit the result: the app itself has no build step.
// The shared files (nostr bundle, gun, qrcode) come from the framework.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const nm = (p) => path.join(root, 'node_modules', p);
const out = (p) => path.join(root, 'apps/loadout', p);
const version = (pkg) => createRequire(import.meta.url)(nm(`${pkg}/package.json`)).version;
const stripMap = (s) => s.replace(/\n\/\/# sourceMappingURL=.*\s*$/, '\n');

const files = [
  ['marked/lib/marked.esm.js', 'vendor/marked.esm.js'],
  ['dompurify/dist/purify.es.mjs', 'vendor/purify.es.mjs'],
  ['qrcode-generator/dist/qrcode.mjs', 'vendor/qrcode.mjs'],
];
for (const [from, to] of files) {
  fs.mkdirSync(path.dirname(out(to)), { recursive: true });
  fs.writeFileSync(out(to), stripMap(fs.readFileSync(nm(from), 'utf8')));
}

// Loadout's own sprite: <svg><use href="icons.svg#name"/></svg>
const ICONS = [
  'plus', 'minus', 'check', 'x', 'share-2', 'ellipsis', 'trash-2', 'lock', 'globe', 'list-checks',
  'notebook-pen', 'package', 'user', 'settings', 'copy', 'qr-code', 'grip-vertical', 'chevron-left',
  'cloud', 'cloud-off', 'download', 'upload', 'key-round', 'eye', 'pencil', 'link', 'sun', 'moon',
  'log-out', 'shield', 'refresh-cw', 'external-link', 'pin', 'pin-off', 'search', 'file-text', 'languages',
  'layout-grid', 'send', 'gamepad-2', 'message-square-lock', 'sticky-note', 'radio-tower',
  'users', 'user-plus', 'user-check', 'users-round',
];
const symbols = ICONS.map((name) => {
  const svg = fs.readFileSync(nm(`lucide-static/icons/${name}.svg`), 'utf8');
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s*\n\s*/g, '');
  return `<symbol id="${name}" viewBox="0 0 24 24">${body}</symbol>`;
});
fs.writeFileSync(
  out('icons.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n<!-- Lucide icons (ISC) -->\n${symbols.join('\n')}\n</svg>\n`,
);

fs.writeFileSync(
  out('vendor/LICENSES.md'),
  `# Third-party files

Generated by \`npm run vendor\` (scripts/vendor.mjs). Do not edit by hand.

| File | Package | License |
|------|---------|---------|
| marked.esm.js | marked ${version('marked')} | MIT |
| purify.es.mjs | dompurify ${version('dompurify')} | MPL-2.0 OR Apache-2.0 |
| qrcode.mjs | qrcode-generator ${version('qrcode-generator')} | MIT |
| ../icons.svg | lucide-static ${version('lucide-static')} | ISC |
`,
);
console.log(`vendored ${files.length} files and ${ICONS.length} icons`);
